apiVersion: apps/v1
kind: Deployment
metadata:
  name: osquery-deployment
  labels:
    app: osquery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osquery
  template:
    metadata:
      labels:
        app: osquery
    spec:
      shareProcessNamespace: true
      containers:
      - name: nginx
        image: nginx
      - name: osquery-exporter
        image: kubeir/osquery-exporter
        ports:
          - containerPort: 5000
      - name: sleeper
        image: docker.io/prateeknischal/sleeper
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
          - name: configmap
            mountPath: /etc/config.yml
          - name: dockersock
            mountPath: "/var/run/docker.sock"
      volumes:
      - name: configmap
        configMap:
          name: test
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

